spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dms_dev
    username: postgres
    password: Sachin29

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.enterprise.dms: DEBUG
    org.springframework.web: DEBUG
