server:
  port: 8081
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

spring:
  application:
    name: document-management-system

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/dms
    username: postgres
    password: Sachin29
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Application specific properties
app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400000 # 24 hours

  file:
    upload-dir: ./uploads
    max-size: 104857600 # 100MB
    allowed-types: pdf,doc,docx,txt,jpg,png

  workflow:
    default-timeout: 72 # hours
    escalation-enabled: true

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.enterprise.dms: DEBUG
    org.springframework.security: DEBUG
    org.springframework.statemachine: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/dms.log
