spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/dms}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Sachin29}

  jpa:
    show-sql: false

logging:
  level:
    com.enterprise.dms: INFO
    org.springframework: WARN
